version: '3.8'

services:
  rerank-api:
    build: .
    image: rerank-api:latest
    container_name: rerank-api
    ports:
      - "7987:7987"
    user: "1000:1000"
    environment:
      - HOST=0.0.0.0
      - PORT=7987
      - WORKERS=1
      - RERANKER_MODEL_NAME=maidalun1020/bce-reranker-base_v1
      - RERANKER_MODELS_DIR=/home/appuser/.cache/huggingface/models
      - HF_HOME=/home/appuser/.cache/huggingface
      # Explicitly set to use CPU
      - CUDA_VISIBLE_DEVICES=-1
    volumes:
      - huggingface-cache:/home/appuser/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7987/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  huggingface-cache:
    driver: local